/* ============================================================
   Formulas — Formula Library data
   ============================================================ */
const Formulas = [
  { name: 'SUM', category: 'Math', difficulty: 'Beginner', syntax: '=SUM(range)',
    desc: 'Adds all numbers in a range.',
    args: 'range — One or more cell ranges to add.',
    example: '=SUM(A1:A10)',
    business: '=SUM(Sales[B2:B100]) — Total sales for a region.',
    error: 'Ignores text cells. Returns 0 if range is empty.' },
  { name: 'AVERAGE', category: 'Math', difficulty: 'Beginner', syntax: '=AVERAGE(range)',
    desc: 'Returns the mean of numbers in a range.',
    args: 'range — Cells to average.',
    example: '=AVERAGE(B1:B10)',
    business: '=AVERAGE(Sales[C2:C100]) — Average sale amount.',
    error: 'Ignores text. Returns #DIV/0! if range is empty.' },
  { name: 'COUNT', category: 'Math', difficulty: 'Beginner', syntax: '=COUNT(range)',
    desc: 'Counts cells with numbers.',
    args: 'range — Range to count numbers in.',
    example: '=COUNT(A1:A20)',
    business: '=COUNT(Responses[A2:A500]) — Count numeric responses.',
    error: 'Does not count text or blank cells.' },
  { name: 'COUNTA', category: 'Math', difficulty: 'Beginner', syntax: '=COUNTA(range)',
    desc: 'Counts non-empty cells (any type).',
    args: 'range — Range to count.',
    example: '=COUNTA(A1:A20)',
    business: '=COUNTA(Employees[A2:A100]) — Count employees listed.',
    error: 'Counts zeros as non-empty.' },
  { name: 'MIN / MAX', category: 'Math', difficulty: 'Beginner', syntax: '=MIN(range) / =MAX(range)',
    desc: 'Returns smallest/largest value in a range.',
    args: 'range — Cells to check.',
    example: '=MIN(A1:A10)',
    business: '=MIN(Prices[A2:A500]) — Lowest price.',
    error: 'Ignores text. Returns 0 if range has no numbers.' },
  { name: 'ROUND', category: 'Math', difficulty: 'Beginner', syntax: '=ROUND(num, digits)',
    desc: 'Rounds a number to specified decimal places.',
    args: 'num — Number to round. digits — Decimal places.',
    example: '=ROUND(3.14159, 2)',
    business: '=ROUND(Total*0.07, 2) — Round tax to 2 decimals.',
    error: 'Digits can be negative (rounds left of decimal).' },
  { name: 'TODAY', category: 'Date', difficulty: 'Beginner', syntax: '=TODAY()',
    desc: 'Returns current date. Updates daily.',
    args: 'No arguments.',
    example: '=TODAY()',
    business: '=TODAY() — Today\'s date for reports.',
    error: 'No error. Recalculates each day.' },
  { name: 'NOW', category: 'Date', difficulty: 'Beginner', syntax: '=NOW()',
    desc: 'Returns current date and time.',
    args: 'No arguments.',
    example: '=NOW()',
    business: '=NOW() — Timestamp for logs.',
    error: 'No error. Updates on recalculation.' },
  { name: 'IF', category: 'Logical', difficulty: 'Beginner', syntax: '=IF(condition, true_val, false_val)',
    desc: 'Returns one value if condition is true, another if false.',
    args: 'condition — Test. true_val — If true. false_val — If false.',
    example: '=IF(A1>70,"Pass","Fail")',
    business: '=IF(Sales>1000,"Bonus","No Bonus")',
    error: 'Missing arguments cause #VALUE! or #NAME?.' },
  { name: 'SUMIF', category: 'Math', difficulty: 'Intermediate', syntax: '=SUMIF(range, criteria, sum_range)',
    desc: 'Sums cells that meet one condition.',
    args: 'range — Criteria range. criteria — Condition. sum_range — Cells to sum.',
    example: '=SUMIF(A1:A10,">5",B1:B10)',
    business: '=SUMIF(Region,"East",Sales) — East region total.',
    error: 'Range and sum_range must align.' },
  { name: 'SUMIFS', category: 'Math', difficulty: 'Intermediate', syntax: '=SUMIFS(sum_range, crit_range1, crit1, …)',
    desc: 'Sums cells meeting multiple conditions.',
    args: 'sum_range — Cells to sum. crit_range/crit — Pairs of criteria.',
    example: '=SUMIFS(D1:D10,A1:A10,"East",B1:B10,">100")',
    business: '=SUMIFS(Sales,Region,"East",Month,"Jan")',
    error: 'sum_range is first argument (unlike SUMIF).' },
  { name: 'COUNTIF', category: 'Math', difficulty: 'Intermediate', syntax: '=COUNTIF(range, criteria)',
    desc: 'Counts cells matching a condition.',
    args: 'range — Cells to check. criteria — Condition.',
    example: '=COUNTIF(A1:A10,">5")',
    business: '=COUNTIF(Status,"Completed") — Count completed tasks.',
    error: 'Use wildcards * and ? for partial matches.' },
  { name: 'COUNTIFS', category: 'Math', difficulty: 'Intermediate', syntax: '=COUNTIFS(range1, crit1, …)',
    desc: 'Counts cells matching multiple conditions.',
    args: 'Pairs of range/criteria.',
    example: '=COUNTIFS(A1:A10,"East",B1:B10,">100")',
    business: '=COUNTIFS(Region,"East",Sales,">1000")',
    error: 'All ranges must be same size.' },
  { name: 'XLOOKUP', category: 'Lookup', difficulty: 'Intermediate', syntax: '=XLOOKUP(val, lookup, return, if_none)',
    desc: 'Modern lookup. Finds a value and returns a match.',
    args: 'val — Value to find. lookup — Where to search. return — What to return.',
    example: '=XLOOKUP("Bob",A1:A10,B1:B10,"N/A")',
    business: '=XLOOKUP(ProductID,Products[ID],Products[Price],"Not found")',
    error: 'Requires Microsoft 365 / Excel 2021+.' },
  { name: 'VLOOKUP', category: 'Lookup', difficulty: 'Intermediate', syntax: '=VLOOKUP(val, table, col, exact)',
    desc: 'Legacy lookup. Searches first column, returns from column index.',
    args: 'val — Lookup value. table — Table range. col — Column index. exact — TRUE/FALSE.',
    example: '=VLOOKUP("Bob",A1:C10,2,FALSE)',
    business: '=VLOOKUP(EmpID,Data,3,FALSE) — Get employee name.',
    error: 'Only looks right. Breaks if columns inserted. Use FALSE for exact match.' },
  { name: 'IFERROR', category: 'Logical', difficulty: 'Intermediate', syntax: '=IFERROR(val, fallback)',
    desc: 'Returns fallback if formula errors.',
    args: 'val — Formula to check. fallback — Value if error.',
    example: '=IFERROR(A1/B1,0)',
    business: '=IFERROR(VLOOKUP(...),"Not found")',
    error: 'Catches all errors — use carefully.' },
  { name: 'LEFT / RIGHT / MID', category: 'Text', difficulty: 'Beginner', syntax: '=LEFT(text,n) / RIGHT(text,n) / MID(text,start,n)',
    desc: 'Extract characters from text.',
    args: 'text — Source. n — Characters. start — Start position (MID).',
    example: '=LEFT("Hello",3) → Hel',
    business: '=LEFT(Code,3) — Extract prefix.',
    error: 'Returns #VALUE! if start > text length.' },
  { name: 'LEN / TRIM / CLEAN', category: 'Text', difficulty: 'Beginner', syntax: '=LEN(text) / =TRIM(text) / =CLEAN(text)',
    desc: 'Text length, trim spaces, remove non-printable chars.',
    args: 'text — Source text.',
    example: '=TRIM("  hi  ") → "hi"',
    business: '=TRIM(Name) — Clean imported names.',
    error: 'CLEAN removes only non-printable chars; TRIM removes extra spaces.' },
  { name: 'CONCAT / TEXTJOIN', category: 'Text', difficulty: 'Intermediate', syntax: '=CONCAT(a,b) / =TEXTJOIN(delim,ignore,range)',
    desc: 'Combine text. TEXTJOIN lets you specify a delimiter.',
    args: 'delim — Separator. ignore — Ignore empty?. range — Cells to join.',
    example: '=TEXTJOIN(", ",TRUE,A1:A5)',
    business: '=TEXTJOIN("; ",TRUE,Tags) — Combine tags.',
    error: 'TEXTJOIN is Microsoft 365 / Excel 2019+.' },
  { name: 'FIND / SEARCH', category: 'Text', difficulty: 'Intermediate', syntax: '=FIND(find,text) / =SEARCH(find,text)',
    desc: 'Find position of substring. FIND is case-sensitive.',
    args: 'find — Substring. text — Source text.',
    example: '=FIND("o","Hello") → 4',
    business: '=FIND("@",Email) — Get position of @.',
    error: 'Returns #VALUE! if not found. SEARCH is case-insensitive.' },
  { name: 'FILTER', category: 'Dynamic Array', difficulty: 'Advanced', syntax: '=FILTER(range, condition)',
    desc: 'Returns filtered rows from a range.',
    args: 'range — Data. condition — Boolean condition.',
    example: '=FILTER(A1:C10,B1:B10>100)',
    business: '=FILTER(Sales,Sales>1000) — Large sales only.',
    error: 'Requires Microsoft 365. Returns #CALC! if no matches.' },
  { name: 'UNIQUE', category: 'Dynamic Array', difficulty: 'Advanced', syntax: '=UNIQUE(range)',
    desc: 'Returns unique values from a range.',
    args: 'range — Source data.',
    example: '=UNIQUE(A1:A20)',
    business: '=UNIQUE(Regions) — List distinct regions.',
    error: 'Microsoft 365 only.' },
  { name: 'SORT / SORTBY', category: 'Dynamic Array', difficulty: 'Advanced', syntax: '=SORT(range) / =SORTBY(range,by)',
    desc: 'Sort a range by column.',
    args: 'range — Data to sort. by — Column to sort by.',
    example: '=SORT(A1:C10,2,1)',
    business: '=SORT(Sales,3,-1) — Sort by revenue descending.',
    error: 'Microsoft 365 only.' },
  { name: 'LET', category: 'Advanced', difficulty: 'Advanced', syntax: '=LET(name,val,formula)',
    desc: 'Define named variables in formulas for readability.',
    args: 'name — Variable name. val — Value. formula — Final calculation.',
    example: '=LET(tax,0.07,total,A1*1.07)',
    business: '=LET(revenue,Sales*Price,total,revenue*0.9)',
    error: 'Microsoft 365 only. Variable names cannot be cell references.' },
  { name: 'IFNA', category: 'Logical', difficulty: 'Intermediate', syntax: '=IFNA(val, fallback)',
    desc: 'Returns fallback only for #N/A errors.',
    args: 'val — Formula. fallback — Value if #N/A.',
    example: '=IFNA(VLOOKUP(...),"Not found")',
    business: '=IFNA(XLOOKUP(…),"Missing")',
    error: 'Only catches #N/A, not all errors.' },
];