const Lab={
 workbook:null,selection:[2,1],anchor:[2,1],history:[],future:[],filter:'',editing:false,
 init(){try{const saved=JSON.parse(localStorage.getItem('xfa_workbook'));this.workbook=this.valid(saved)?saved:seedWorkbook();}catch{this.workbook=seedWorkbook();}},
 valid(w){try{return w?.version===1&&typeof w.title==='string'&&w.title.length<200&&Array.isArray(w.sheets)&&w.sheets.length>0&&w.sheets.length<=12&&new Set(w.sheets.map(s=>s.id)).size===w.sheets.length&&new Set(w.sheets.map(s=>s.name.toLowerCase())).size===w.sheets.length&&w.sheets.every(s=>/^[a-zA-Z0-9_-]+$/.test(s.id)&&typeof s.name==='string'&&s.name.length>0&&s.name.length<=31&&s.cells&&Object.keys(s.cells).length<=3120&&Object.entries(s.cells).every(([ref,c])=>{const [r,col]=SheetEngine.coord(ref);return /^[A-Z]+[1-9][0-9]*$/.test(ref)&&r<120&&col<26&&c&&['string','number'].includes(typeof c.raw)&&String(c.raw).length<=2000&&(!c.format||['general','number','currency','percent','date','header'].includes(c.format));})&&['widths','heights'].every(key=>!s[key]||Object.entries(s[key]).every(([k,v])=>/^\d+$/.test(k)&&Number.isFinite(v)&&v>=30&&v<=400)))&&w.sheets.some(s=>s.id===w.active);}catch{return false;}},
 sheet(){return this.workbook.sheets.find(s=>s.id===this.workbook.active);},
 save(){try{localStorage.setItem('xfa_workbook',JSON.stringify(this.workbook));const e=document.getElementById('saveState');if(e)e.textContent='Saved on this device';}catch{App.showToast('Storage is full or unavailable. Export your workbook to keep a copy.');}},
 transaction(fn){this.history.push(JSON.stringify(this.workbook));if(this.history.length>40)this.history.shift();this.future=[];fn();this.save();},
 undo(){if(!this.history.length)return;this.future.push(JSON.stringify(this.workbook));this.workbook=JSON.parse(this.history.pop());this.save();this.render();},
 redo(){if(!this.future.length)return;this.history.push(JSON.stringify(this.workbook));this.workbook=JSON.parse(this.future.pop());this.save();this.render();},
 open(id){if(!this.workbook)this.init();if(id&&this.workbook.exercise!==id){const ex=Exercises.find(e=>e.id===id);if(!ex)return;this.transaction(()=>{this.workbook=createExerciseWorkbook(ex);});this.selection=[2,1];this.anchor=[2,1];}App.navigate('lab');},
 load(dataset){this.transaction(()=>{this.workbook=seedWorkbook(dataset);});this.selection=[0,0];this.anchor=[0,0];this.filter='';this.render();},
 reset(){const ex=Exercises.find(e=>e.id===this.workbook.exercise);this.transaction(()=>{this.workbook=ex?createExerciseWorkbook(ex):seedWorkbook(this.workbook.dataset);});this.selection=[2,1];this.anchor=[2,1];this.filter='';this.render();App.showToast('Exercise reset. Undo can restore your previous work.');},
 bounds(){return [Math.min(this.anchor[0],this.selection[0]),Math.min(this.anchor[1],this.selection[1]),Math.max(this.anchor[0],this.selection[0]),Math.max(this.anchor[1],this.selection[1])];},
 forRange(fn){const [r1,c1,r2,c2]=this.bounds();for(let r=r1;r<=r2;r++)for(let c=c1;c<=c2;c++)fn(SheetEngine.address(r,c),r,c);},
 format(value){this.transaction(()=>this.forRange(ref=>{this.sheet().cells[ref]={raw:'',...this.sheet().cells[ref],format:value};}));this.renderGrid();},
 set(ref,raw){if((this.sheet().cells[ref]?.raw??'')===raw)return;this.transaction(()=>{this.sheet().cells[ref]={...this.sheet().cells[ref],raw};});},
 display(value,format){if(typeof value!=='number')return String(value??'');if(format==='currency')return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);if(format==='percent')return new Intl.NumberFormat('en-US',{style:'percent',maximumFractionDigits:2}).format(value);if(format==='date')return new Date(Date.UTC(1899,11,30)+value*86400000).toISOString().slice(0,10);if(format==='number')return new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(value);return String(Math.round(value*1e10)/1e10);},
 render(){if(!this.workbook)this.init();const ex=Exercises.find(e=>e.id===this.workbook.exercise);document.getElementById('labContent').innerHTML=`
 <div class="page-heading"><div><p class="eyebrow">WORKBOOK LAB / LEARN BY DOING</p><h1>${escapeHTML(ex?ex.title:'A little room to experiment.')}</h1></div><span class="save-state" id="saveState">Saved on this device</span></div>
 ${ex?`<div class="exercise-brief"><div><span class="eyebrow">YOUR TASK · ${ex.target}</span><p>${escapeHTML(ex.instruction)}</p><details><summary>Need a hint?</summary><p>${escapeHTML(ex.hint)}</p></details></div><div class="actions"><button class="btn btn-primary" onclick="Lab.check()">Check answer</button><button class="btn" onclick="Lab.reset()">Reset</button><button class="btn btn-quiet" onclick="Lab.solution()">View solution</button></div></div><p id="exerciseFeedback" class="feedback" role="status"></p>`:`<p class="intro">Real cells. Working formulas. A safe place to make mistakes. Choose a dataset or start an exercise.</p>`}
 <div class="workbook"><div class="workbook-title"><strong>${Icons.get('lab')} ${escapeHTML(this.workbook.title)}</strong><span class="small">120 rows × 26 columns · educational subset</span></div>
 <div class="lab-toolbar" aria-label="Workbook tools"><button class="btn btn-sm" onclick="Lab.undo()" ${this.history.length?'':'disabled'} title="Undo (Ctrl/Cmd+Z)">Undo</button><button class="btn btn-sm" onclick="Lab.redo()" ${this.future.length?'':'disabled'}>Redo</button><label class="sr-only" for="cellFormat">Cell format</label><select id="cellFormat" onchange="Lab.format(this.value)"><option value="general">General</option><option value="number">Number</option><option value="currency">Currency</option><option value="percent">Percent</option><option value="date">Date</option><option value="header">Bold / header</option></select><button class="btn btn-sm" onclick="Lab.fillDown()">Fill down</button><button class="btn btn-sm" onclick="Lab.sort()">Sort range A–Z</button><button class="btn btn-sm" onclick="Lab.sizeDialog()">Cell size</button><label class="freeze"><input type="checkbox" ${this.sheet().freeze?'checked':''} onchange="Lab.transaction(()=>Lab.sheet().freeze=this.checked);Lab.renderGrid()"> Freeze row 1</label><label class="sr-only" for="gridFilter">Filter rows in current sheet</label><input id="gridFilter" placeholder="Filter rows…" value="${escapeHTML(this.filter)}" oninput="Lab.filter=this.value;Lab.renderGrid()"></div>
 <div class="formula-bar"><label class="sr-only" for="cellAddress">Cell or range</label><input id="cellAddress" aria-label="Cell or range" value="${SheetEngine.address(...this.selection)}" onkeydown="if(event.key==='Enter')Lab.go(this.value)"><span class="formula-mark">fx</span><label class="sr-only" for="formulaInput">Formula or value</label><input id="formulaInput" aria-label="Formula or value" spellcheck="false" onkeydown="if(event.key==='Enter'){Lab.commitFormula();event.preventDefault();}" onchange="Lab.commitFormula()"><button class="btn btn-sm" onclick="Lab.commitFormula()">Apply</button></div>
 <div id="gridScroll" class="grid-scroll" aria-label="Scrollable worksheet"><table id="sheetGrid" role="grid" aria-label="${escapeHTML(this.sheet().name)} worksheet" aria-rowcount="120" aria-colcount="26"></table></div>
 <div class="sheet-tabs" role="tablist" aria-label="Worksheets">${this.workbook.sheets.map(s=>`<button role="tab" aria-selected="${s.id===this.workbook.active}" onclick="Lab.switchSheet('${s.id}')">${Icons.get('table')}${escapeHTML(s.name)}</button>`).join('')}<button class="btn btn-sm" onclick="Lab.addSheet()" aria-label="Add sheet">+</button><button class="btn btn-sm" onclick="Lab.rename()">Rename</button><button class="btn btn-sm" onclick="Lab.removeSheet()" ${this.workbook.sheets.length<2?'disabled':''}>Remove</button></div>
 <div class="lab-status"><span id="selectionStatus"></span><span>Shift + arrows: select range · Enter: edit / commit · Ctrl/Cmd + D: fill</span></div></div>
 <div class="lab-bottom"><div class="actions"><label class="btn">Import CSV<input type="file" accept=".csv,text/csv" class="sr-only" onchange="Lab.importCSV(this.files[0])"></label><button class="btn" onclick="Lab.exportCSV()">Export CSV</button><button class="btn" onclick="Lab.exportWorkbook()">Export workbook</button><label class="btn">Import workbook<input type="file" accept=".json,application/json" class="sr-only" onchange="Lab.importWorkbook(this.files[0])"></label></div><label>Sample dataset <select onchange="if(this.value)Lab.load(this.value)"><option value="">Choose…</option>${Object.entries(Datasets).map(([k,d])=>`<option value="${k}">${d.name}</option>`).join('')}</select></label></div><p class="small">CSV import treats formulas as text. Workbook JSON preserves formulas and formatting. For PivotTables, charts, Power Query and dynamic arrays, use Excel; the Lab teaches a focused formula and editing subset. On phones, scroll the sheet horizontally.</p>`;
 this.renderGrid();
 },
 renderGrid(){const grid=document.getElementById('sheetGrid');if(!grid)return;const sheet=this.sheet(),calc=SheetEngine.calculator(this.workbook);this.calc=calc;const scroll=document.getElementById('gridScroll'),top=scroll.scrollTop,left=scroll.scrollLeft;let html='<thead><tr><th aria-label="Row numbers"></th>';for(let c=0;c<26;c++)html+=`<th scope="col" style="min-width:${sheet.widths?.[c]||110}px;width:${sheet.widths?.[c]||110}px">${SheetEngine.col(c)}<span class="resize col-resize" role="separator" aria-label="Resize column ${SheetEngine.col(c)}" onpointerdown="Lab.resize(event,'column',${c})"></span></th>`;html+='</tr></thead><tbody>';for(let r=0;r<120;r++){if(this.filter&&r>0&&!Array.from({length:26},(_,c)=>String(calc.get(sheet,SheetEngine.address(r,c)))).join(' ').toLowerCase().includes(this.filter.toLowerCase()))continue;html+=`<tr style="height:${sheet.heights?.[r]||30}px" class="${r===0&&sheet.freeze?'frozen':''}"><th scope="row">${r+1}<span class="resize row-resize" onpointerdown="Lab.resize(event,'row',${r})" aria-hidden="true"></span></th>`;for(let c=0;c<26;c++){const ref=SheetEngine.address(r,c),data=sheet.cells[ref]||{},v=calc.get(sheet,ref);html+=`<td role="gridcell" class="${data.format==='header'?'cell-header ':''}${typeof v==='number'?'numeric ':''}${String(v).startsWith('#')?'cell-error':''}" data-ref="${ref}" aria-selected="false"><input aria-label="${ref}" data-r="${r}" data-c="${c}" tabindex="-1" value="${escapeHTML(this.display(v,data.format))}" spellcheck="false" onfocus="Lab.select(${r},${c},false)" onpointerdown="Lab.pointer(event,${r},${c})" ondblclick="Lab.edit(this)" onkeydown="Lab.key(event,${r},${c})" oninput="Lab.editing=true" onchange="Lab.set('${ref}',this.value)" onblur="Lab.blur(this)" oncopy="Lab.copy(event)" oncut="Lab.copy(event,true)" onpaste="Lab.paste(event)"></td>`;}html+='</tr>';}grid.innerHTML=html+'</tbody>';scroll.scrollTop=top;scroll.scrollLeft=left;this.highlight();const undo=document.querySelector('.lab-toolbar button');if(undo)undo.disabled=!this.history.length;const redo=document.querySelectorAll('.lab-toolbar button')[1];if(redo)redo.disabled=!this.future.length;},
 pointer(e,r,c){if(e.shiftKey){e.preventDefault();this.select(r,c,true);}else this.select(r,c,false);},
 select(r,c,extend){if(this.editing)return;this.selection=[r,c];if(!extend)this.anchor=[r,c];this.highlight();},
 highlight(){const [r1,c1,r2,c2]=this.bounds();let count=0,sum=0;document.querySelectorAll('#sheetGrid td').forEach(td=>{const [r,c]=SheetEngine.coord(td.dataset.ref),selected=r>=r1&&r<=r2&&c>=c1&&c<=c2;td.classList.toggle('selected',selected);td.setAttribute('aria-selected',selected);td.querySelector('input').tabIndex=r===this.selection[0]&&c===this.selection[1]?0:-1;if(selected){const v=this.calc.get(this.sheet(),td.dataset.ref);if(typeof v==='number'){count++;sum+=v;}}});const ref=SheetEngine.address(...this.selection);document.getElementById('cellAddress').value=r1===r2&&c1===c2?ref:SheetEngine.address(r1,c1)+':'+SheetEngine.address(r2,c2);document.getElementById('formulaInput').value=this.sheet().cells[ref]?.raw??'';document.getElementById('selectionStatus').textContent=`${count} numeric cells · Sum ${Math.round(sum*100)/100}`;},
 edit(input){this.editing=true;input.value=this.sheet().cells[SheetEngine.address(+input.dataset.r,+input.dataset.c)]?.raw??'';input.select();},
 blur(input){if(this.editing){this.set(SheetEngine.address(+input.dataset.r,+input.dataset.c),input.value);this.editing=false;this.renderGrid();}},
 key(e,r,c){const mod=e.ctrlKey||e.metaKey;if(mod&&['z','y','d'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='d')this.fillDown();else if(e.key.toLowerCase()==='y'||e.shiftKey)this.redo();else this.undo();return;}if(e.key==='Escape'){this.editing=false;this.renderGrid();return;}if((e.key==='Enter'||e.key==='F2')&&!this.editing){e.preventDefault();this.edit(e.target);return;}if(this.editing&&!['Enter','Tab'].includes(e.key))return;const dirs={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1],Enter:[1,0],Tab:[0,e.shiftKey?-1:1]};if(dirs[e.key]){e.preventDefault();if(this.editing){this.set(SheetEngine.address(r,c),e.target.value);this.editing=false;this.renderGrid();}const [dr,dc]=dirs[e.key],rr=Math.max(0,Math.min(119,r+dr)),cc=Math.max(0,Math.min(25,c+dc)),old=[...this.anchor];const input=document.querySelector(`[data-ref="${SheetEngine.address(rr,cc)}"] input`);input?.focus();this.selection=[rr,cc];this.anchor=e.shiftKey&&e.key!=='Tab'?old:[rr,cc];this.highlight();}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();this.transaction(()=>this.forRange(ref=>delete this.sheet().cells[ref]));this.renderGrid();}else if(e.key.length===1&&!mod&&!e.altKey){this.editing=true;e.target.value='';}},
 commitFormula(){const raw=document.getElementById('formulaInput').value;this.set(SheetEngine.address(...this.selection),raw);this.renderGrid();},
 go(value){try{const parts=value.toUpperCase().split(':'),a=SheetEngine.coord(parts[0]),b=SheetEngine.coord(parts[1]||parts[0]);if([...a,...b].some(n=>n<0)||a[0]>119||b[0]>119||a[1]>25||b[1]>25)throw Error();this.anchor=a;this.selection=b;this.highlight();document.querySelector(`[data-ref="${SheetEngine.address(...b)}"]`)?.scrollIntoView({block:'nearest',inline:'nearest'});}catch{App.showToast('Use A1 through Z120, or a range such as B2:B10.');}},
 copy(e,cut=false){if(this.editing)return;e.preventDefault();const [r1,c1,r2,c2]=this.bounds(),rows=[];for(let r=r1;r<=r2;r++){const row=[];for(let c=c1;c<=c2;c++)row.push(this.calc.get(this.sheet(),SheetEngine.address(r,c)));rows.push(row.join('\t'));}e.clipboardData.setData('text/plain',rows.join('\n'));if(cut){this.transaction(()=>this.forRange(ref=>delete this.sheet().cells[ref]));this.renderGrid();}},
 paste(e){if(this.editing)return;e.preventDefault();const rows=e.clipboardData.getData('text/plain').replace(/\r/g,'').split('\n').map(r=>r.split('\t'));this.transaction(()=>rows.forEach((row,dr)=>row.forEach((raw,dc)=>{const r=this.selection[0]+dr,c=this.selection[1]+dc;if(r<120&&c<26)this.sheet().cells[SheetEngine.address(r,c)]={raw};})));this.renderGrid();},
 fillDown(){const [r1,c1,r2,c2]=this.bounds();if(r1===r2){App.showToast('Select at least two rows, with the source value in the top row.');return;}this.transaction(()=>{for(let c=c1;c<=c2;c++){const source=this.sheet().cells[SheetEngine.address(r1,c)]||{raw:''};for(let r=r1+1;r<=r2;r++)this.sheet().cells[SheetEngine.address(r,c)]={...source,raw:String(source.raw).startsWith('=')?SheetEngine.shift(source.raw,r-r1):source.raw};}});this.renderGrid();},
 sort(){const [r1,c1,r2,c2]=this.bounds();if(r1===r2)return App.showToast('Select a rectangular data range, excluding headers. Sort converts selected formulas to values.');const rows=[];for(let r=r1;r<=r2;r++)rows.push(Array.from({length:c2-c1+1},(_,i)=>this.calc.get(this.sheet(),SheetEngine.address(r,c1+i))));rows.sort((a,b)=>typeof a[0]==='number'&&typeof b[0]==='number'?a[0]-b[0]:String(a[0]).localeCompare(String(b[0])));this.transaction(()=>rows.forEach((row,i)=>row.forEach((raw,j)=>this.sheet().cells[SheetEngine.address(r1+i,c1+j)]={...this.sheet().cells[SheetEngine.address(r1+i,c1+j)],raw:String(raw)})));this.renderGrid();App.showToast('Selected rows sorted by their first column. Formulas in this range became values. Undo is available.');},
 resize(e,type,index){e.preventDefault();const start=type==='column'?e.clientX:e.clientY,sheet=this.sheet(),key=type==='column'?'widths':'heights',initial=sheet[key]?.[index]||(type==='column'?110:30);const end=ev=>{document.removeEventListener('pointerup',end);this.transaction(()=>{sheet[key]||={};sheet[key][index]=Math.max(type==='column'?60:30,Math.min(type==='column'?400:140,initial+(type==='column'?ev.clientX:ev.clientY)-start));});this.renderGrid();};document.addEventListener('pointerup',end,{once:true});},
 switchSheet(id){this.workbook.active=id;this.filter='';this.selection=[0,0];this.anchor=[0,0];this.save();this.render();},
 addSheet(){if(this.workbook.sheets.length>=12)return App.showToast('This learning workbook supports up to 12 sheets.');this.transaction(()=>{const id='s'+Date.now();let n=1;while(this.workbook.sheets.some(s=>s.name==='Sheet '+n))n++;this.workbook.sheets.push({id,name:'Sheet '+n,cells:{},widths:{},heights:{},freeze:true});this.workbook.active=id;});this.render();},
 sizeDialog(){App.dialog('Size selected rows and columns',`<label>Column width (60–400 pixels)<input id="columnWidth" type="number" min="60" max="400" value="110"></label><label>Row height (30–140 pixels)<input id="rowHeight" type="number" min="30" max="140" value="30"></label><button class="btn btn-primary" onclick="Lab.applySize()">Apply size</button>`);},
 applySize(){const width=Number(document.getElementById('columnWidth').value),height=Number(document.getElementById('rowHeight').value);if(width<60||width>400||height<30||height>140)return App.showToast('Choose dimensions within the displayed limits.');const [r1,c1,r2,c2]=this.bounds();this.transaction(()=>{this.sheet().widths||={};this.sheet().heights||={};for(let r=r1;r<=r2;r++)this.sheet().heights[r]=height;for(let c=c1;c<=c2;c++)this.sheet().widths[c]=width;});App.closeDialog();this.renderGrid();},
 rename(){App.dialog('Rename worksheet',`<label>Sheet name<input id="sheetName" maxlength="31" value="${escapeHTML(this.sheet().name)}"></label><p class="small">Cross-sheet references are updated automatically.</p><button class="btn btn-primary" onclick="Lab.applyRename()">Save name</button>`);},
 applyRename(){const name=document.getElementById('sheetName').value.trim();if(!name||/[\[\]:*?/\\!']/.test(name)||this.workbook.sheets.some(s=>s.id!==this.sheet().id&&s.name.toLowerCase()===name.toLowerCase()))return App.showToast('Use a unique name without spreadsheet punctuation.');const old=this.sheet().name;this.transaction(()=>{for(const s of this.workbook.sheets)for(const cell of Object.values(s.cells))if(String(cell.raw).startsWith('='))cell.raw=cell.raw.split(/("(?:[^"]|"")*")/g).map((part,i)=>i%2?part:part.replace(new RegExp("(?:'"+old.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+"'|\\b"+old.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+")!",'gi'),"'"+name+"'!")).join('');this.sheet().name=name;});App.closeDialog();this.render();},
 removeSheet(){if(this.workbook.sheets.length<2)return;this.transaction(()=>{this.workbook.sheets=this.workbook.sheets.filter(s=>s.id!==this.workbook.active);this.workbook.active=this.workbook.sheets[0].id;});this.render();App.showToast('Sheet removed. Undo restores it. References to it show #REF!.');},
 check(){const ex=Exercises.find(e=>e.id===this.workbook.exercise);if(!ex)return;const work=this.workbook.sheets.find(s=>s.id==='work'),raw=work?.cells[ex.target]?.raw||'',value=work?SheetEngine.calculator(this.workbook).get(work,ex.target):'#REF!',expected=exerciseExpected(ex);const ok=ex.kind==='state'?ex.check(this):String(raw).startsWith('=')&&(!ex.solution.includes('Data!')||/[A-Z]+\$?\d+/i.test(String(raw)))&&(typeof expected==='number'?typeof value==='number'&&Math.abs(value-expected)<1e-7:String(value)===String(expected));const out=document.getElementById('exerciseFeedback');out.className='feedback '+(ok?'success':'warning');out.textContent=ok?(ex.kind==='state'?'Correct. Your workbook matches the requested state.':'Correct. Your formula produces the expected result.'):(ex.kind==='state'?'Not yet. '+ex.instruction:'Not yet. Enter a formula in Analysis!'+ex.target+'. Check the source range and criteria.');if(ok){const done=Store.read('xfa_exercises',{});done[ex.id]={completed:true,at:Date.now()};Store.write('xfa_exercises',done);}},
 solution(){const ex=Exercises.find(e=>e.id===this.workbook.exercise);App.dialog('Worked solution',`<p>${escapeHTML(ex.instruction)}</p><pre>${escapeHTML(ex.solution)}</pre><p>Expected result: <strong>${escapeHTML(ex.kind==='state'?'Workbook state matches the task':exerciseExpected(ex))}</strong></p><p>Compare each reference and criterion with your attempt. Then close this explanation and rebuild the formula yourself.</p>`);},
 download(name,text,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},
 exportCSV(){const cells=Object.keys(this.sheet().cells).map(SheetEngine.coord),mr=Math.max(0,...cells.map(c=>c[0])),mc=Math.max(0,...cells.map(c=>c[1]));const rows=Array.from({length:mr+1},(_,r)=>Array.from({length:mc+1},(_,c)=>{const v=this.calc.get(this.sheet(),SheetEngine.address(r,c));return typeof v==='string'&&/^[=+@\-\t\r]/.test(v)?"'"+v:v;}));this.download('practice.csv',SheetEngine.csvWrite(rows),'text/csv');},
 async importCSV(file){if(!file)return;if(file.size>500000)return App.showToast('Choose a CSV under 500 KB.');try{const rows=SheetEngine.csvParse(await file.text());if(rows.length>120||rows.some(r=>r.length>26))throw Error('Limit: 120 rows and 26 columns.');this.transaction(()=>{this.sheet().cells={};rows.forEach((row,r)=>row.forEach((raw,c)=>this.sheet().cells[SheetEngine.address(r,c)]={raw:/^[=+@]/.test(raw)?"'"+raw:raw}));this.workbook.exercise=null;});this.render();}catch(e){App.showToast('Import failed: '+e.message);}},
 exportWorkbook(){this.download('workbook.json',JSON.stringify(this.workbook,null,2),'application/json');},
 async importWorkbook(file){if(!file)return;try{if(file.size>1000000)throw Error('Maximum file size is 1 MB.');const w=JSON.parse(await file.text());if(!this.valid(w))throw Error('Invalid workbook schema.');for(const s of w.sheets){if(!/^[a-zA-Z0-9_-]+$/.test(s.id))throw Error('Invalid sheet ID.');for(const [ref,data] of Object.entries(s.cells)){const [r,c]=SheetEngine.coord(ref);if(r<0||r>=120||c<0||c>=26||!['string','number'].includes(typeof data.raw)||String(data.raw).length>2000)throw Error('Invalid cell.');}s.widths={};s.heights={};}this.transaction(()=>this.workbook=w);this.render();}catch(e){App.showToast('Import failed: '+e.message);}}
};
