const SkillExercises=[
{id:'skill-navigation',title:'Go directly to a cell',topic:'Navigation',target:'C8',instruction:'On Analysis, use the name box to select C8. Check your answer without changing any values.',hint:'The name box is at the left of the formula bar. Type C8 and press Enter.',solution:'Select C8 using the name box.',check:lab=>lab.workbook.active==='work'&&lab.selection.join(',')==='7,2'},
{id:'skill-range',title:'Select a rectangular range',topic:'Selection',target:'B2:C5',instruction:'On Analysis, select exactly B2:C5. Use the name box or Shift with arrow keys.',hint:'Both endpoints are included: four rows and two columns.',solution:'Type B2:C5 in the name box and press Enter.',check:lab=>lab.workbook.active==='work'&&lab.bounds().join(',')==='1,1,4,2'},
{id:'skill-entry',title:'Enter a clear column label',topic:'Data entry',target:'B3',instruction:'Enter Revenue as plain text in Analysis!B3.',hint:'Select B3 and type the label, then commit with Enter.',solution:'Revenue',check:lab=>lab.workbook.sheets.find(s=>s.id==='work')?.cells.B3?.raw==='Revenue'},
{id:'skill-percent',title:'Format a ratio as a percentage',topic:'Formatting',target:'B3',instruction:'Enter 0.15 in Analysis!B3 and apply Percent. It should display 15% while retaining 0.15.',hint:'Formatting changes presentation, not the stored value.',solution:'Store 0.15 in B3 and choose Percent.',check:lab=>{const c=lab.workbook.sheets.find(s=>s.id==='work')?.cells.B3;return Number(c?.raw)===.15&&c?.format==='percent';}},
{id:'skill-currency',title:'Format a price as currency',topic:'Formatting',target:'B3',instruction:'Enter 1250 in Analysis!B3 and apply Currency. Do not type a dollar sign into the value.',hint:'Use the format selector after entering the number.',solution:'Store 1250 in B3 and choose Currency.',check:lab=>{const c=lab.workbook.sheets.find(s=>s.id==='work')?.cells.B3;return Number(c?.raw)===1250&&c?.format==='currency';}},
{id:'skill-date',title:'Display a date serial',topic:'Dates',target:'B3',instruction:'Enter =DATE(2026,3,1) in Analysis!B3 and apply Date.',hint:'DATE constructs a number; the format makes it readable as a calendar date.',solution:'=DATE(2026,3,1), with Date format.',check:lab=>{const s=lab.workbook.sheets.find(s=>s.id==='work');return !!s&&SheetEngine.calculator(lab.workbook).get(s,'B3')===46082&&s.cells.B3.format==='date';}},
{id:'skill-relative',title:'Fill a relative reference',topic:'References',target:'C2:C5',instruction:'On Analysis, enter =A2*B2 in C2. Select C2:C5 and Fill down. Each row should multiply its own units and price.',hint:'A2 and B2 move to A3 and B3 when filled one row down.',solution:'C2 =A2*B2; C3 =A3*B3; C4 =A4*B4; C5 =A5*B5.',seed:{A1:{raw:'Units',format:'header'},B1:{raw:'Price',format:'header'},C1:{raw:'Revenue',format:'header'},A2:{raw:'2'},A3:{raw:'3'},A4:{raw:'4'},A5:{raw:'5'},B2:{raw:'10'},B3:{raw:'20'},B4:{raw:'30'},B5:{raw:'40'}},check:lab=>{const s=lab.workbook.sheets.find(s=>s.id==='work'),c=SheetEngine.calculator(lab.workbook);return !!s&&[20,60,120,200].every((v,i)=>String(s.cells['C'+(i+2)]?.raw).startsWith('=')&&c.get(s,'C'+(i+2))===v);}},
{id:'skill-absolute',title:'Keep the tax rate fixed',topic:'References',target:'C2:C5',instruction:'Revenue is in B2:B5 and a 7% tax rate is in F2. Enter =B2*$F$2 in C2, then fill C2:C5.',hint:'Both dollar signs keep the tax rate in F2 while B2 moves down.',solution:'Use =B2*$F$2 in C2, then Fill down through C5.',seed:{B1:{raw:'Revenue',format:'header'},C1:{raw:'Tax',format:'header'},F1:{raw:'Tax rate',format:'header'},B2:{raw:'100'},B3:{raw:'200'},B4:{raw:'300'},B5:{raw:'400'},F2:{raw:'0.07',format:'percent'}},check:lab=>{const s=lab.workbook.sheets.find(s=>s.id==='work'),c=SheetEngine.calculator(lab.workbook);return !!s&&[7,14,21,28].every((v,i)=>String(s.cells['C'+(i+2)]?.raw).includes('$F$2')&&Math.abs(c.get(s,'C'+(i+2))-v)<1e-8);}},
{id:'skill-sort',title:'Sort whole records together',topic:'Sorting',target:'A2:B5',instruction:'Select Analysis!A2:B5 and sort A–Z. Keep each product paired with its quantity. Exclude the header row.',hint:'Select both columns before sorting so the relationships stay intact.',solution:'Cable 7; Desk 2; Ink 9; Paper 4.',seed:{A1:{raw:'Product',format:'header'},B1:{raw:'Units',format:'header'},A2:{raw:'Paper'},B2:{raw:'4'},A3:{raw:'Desk'},B3:{raw:'2'},A4:{raw:'Ink'},B4:{raw:'9'},A5:{raw:'Cable'},B5:{raw:'7'}},check:lab=>{const s=lab.workbook.sheets.find(s=>s.id==='work');return !!s&&[['Cable','7'],['Desk','2'],['Ink','9'],['Paper','4']].every((row,i)=>row.every((v,c)=>s.cells[SheetEngine.address(i+1,c)]?.raw===v));}},
{id:'skill-filter',title:'Narrow a table without deleting',topic:'Filtering',target:'Data sheet',instruction:'Switch to Data and type East into Filter rows. Leave the underlying records intact.',hint:'Filtering hides rows; it should not erase source cells.',solution:'On Data, enter East in Filter rows.',check:lab=>lab.workbook.active==='data'&&lab.filter.toLowerCase()==='east'&&Object.keys(lab.sheet().cells).length===732},
{id:'skill-sheet',title:'Add an assumptions worksheet',topic:'Worksheets',target:'New sheet',instruction:'Add a worksheet, then rename it Assumptions.',hint:'Use + beside the worksheet tabs, then Rename.',solution:'Add a third sheet named Assumptions.',check:lab=>lab.workbook.sheets.some(s=>s.name==='Assumptions')},
{id:'skill-freeze',title:'Keep table headers visible',topic:'Navigation',target:'Data sheet',instruction:'On Data, enable Freeze row 1. Scroll down to confirm the column labels stay visible.',hint:'Freeze affects scrolling, not whether cells can be edited.',solution:'Select Data and enable Freeze row 1.',check:lab=>lab.workbook.active==='data'&&lab.sheet().freeze===true}
].map(e=>({...e,dataset:'retail',kind:'state'}));
Exercises.push(...SkillExercises);
const LessonPracticeLinks={'micro-fundamentals-1':'skill-navigation','micro-fundamentals-2':'skill-sheet','micro-fundamentals-3':'skill-range','micro-fundamentals-4':'skill-range','micro-fundamentals-5':'ex-015','micro-fundamentals-6':'skill-entry','micro-fundamentals-7':'skill-entry','micro-fundamentals-8':'skill-freeze','micro-fundamentals-10':'skill-navigation','micro-formatting-1':'skill-percent','micro-formatting-2':'skill-currency','micro-formatting-5':'skill-date','micro-formula-foundations-3':'skill-relative','micro-formula-foundations-4':'skill-absolute'};
for(const [id,ex] of Object.entries(LessonPracticeLinks)){const l=getAllLessons().find(l=>l.id===id);if(l)getLesson(l.levelId,id).exercise=ex;}
function createExerciseWorkbook(ex){const w=seedWorkbook(ex.dataset);w.exercise=ex.id;w.active='work';w.sheets[1].cells=ex.seed?JSON.parse(JSON.stringify(ex.seed)):{A1:{raw:ex.title,format:'header'},A3:{raw:'Your answer'}};w.sheets[1].widths={0:180};if(ex.id==='skill-freeze')w.sheets[0].freeze=false;return w;}
