/* ============================================================
   Shortcuts — Keyboard shortcut library data
   ============================================================ */
const Shortcuts = [
  { category: 'Navigation', items: [
    { keys: ['Ctrl'], desc: 'Open file', winMac: 'Win' },
    { keys: ['Ctrl+S'], desc: 'Save', winMac: 'Win/Mac' },
    { keys: ['Ctrl+O'], desc: 'Open file', winMac: 'Win' },
    { keys: ['Ctrl+N'], desc: 'New workbook', winMac: 'Win/Mac' },
    { keys: ['Ctrl+W'], desc: 'Close workbook', winMac: 'Win/Mac' },
    { keys: ['Ctrl+F'], desc: 'Find', winMac: 'Mac: Cmd+F' },
    { keys: ['Ctrl+H'], desc: 'Find & Replace', winMac: 'Mac: Cmd+H' },
    { keys: ['Ctrl+Home'], desc: 'Go to A1', winMac: 'Win/Mac' },
    { keys: ['Ctrl+End'], desc: 'Go to last cell', winMac: 'Win/Mac' },
    { keys: ['Ctrl+Arrow'], desc: 'Go to edge of data', winMac: 'Win/Mac' },
    { keys: ['Ctrl+PageUp/Down'], desc: 'Switch sheets', winMac: 'Win/Mac' },
    { keys: ['F5'], desc: 'Go To dialog', winMac: 'Win/Mac' },
    { keys: ['F2'], desc: 'Edit cell', winMac: 'Win/Mac' },
  ]},
  { category: 'Selection', items: [
    { keys: ['Ctrl+A'], desc: 'Select all', winMac: 'Win/Mac' },
    { keys: ['Shift+Click'], desc: 'Select range', winMac: 'Win/Mac' },
    { keys: ['Ctrl+Shift+Arrow'], desc: 'Select to data edge', winMac: 'Win/Mac' },
    { keys: ['Ctrl+Space'], desc: 'Select entire column', winMac: 'Win/Mac' },
    { keys: ['Shift+Space'], desc: 'Select entire row', winMac: 'Win/Mac' },
    { keys: ['Alt+;'], desc: 'Select visible cells only', winMac: 'Mac: Cmd+Shift+Z' },
  ]},
  { category: 'Editing', items: [
    { keys: ['Ctrl+C'], desc: 'Copy', winMac: 'Win/Mac' },
    { keys: ['Ctrl+X'], desc: 'Cut', winMac: 'Win/Mac' },
    { keys: ['Ctrl+V'], desc: 'Paste', winMac: 'Win/Mac' },
    { keys: ['Ctrl+Z'], desc: 'Undo', winMac: 'Mac: Cmd+Z' },
    { keys: ['Ctrl+Y'], desc: 'Redo', winMac: 'Mac: Cmd+Shift+Z' },
    { keys: ['Ctrl+D'], desc: 'Fill down', winMac: 'Mac: Cmd+D' },
    { keys: ['Ctrl+R'], desc: 'Fill right', winMac: 'Mac: Cmd+R' },
    { keys: ['Ctrl+Enter'], desc: 'Fill selection with entry', winMac: 'Win/Mac' },
    { keys: ['Alt+Enter'], desc: 'New line in cell', winMac: 'Mac: Ctrl+Option+Enter' },
  ]},
  { category: 'Formatting', items: [
    { keys: ['Ctrl+B'], desc: 'Bold', winMac: 'Win/Mac' },
    { keys: ['Ctrl+I'], desc: 'Italic', winMac: 'Win/Mac' },
    { keys: ['Ctrl+U'], desc: 'Underline', winMac: 'Win/Mac' },
    { keys: ['Ctrl+1'], desc: 'Format Cells dialog', winMac: 'Mac: Cmd+1' },
    { keys: ['Ctrl+Shift+$'], desc: 'Currency format', winMac: 'Win/Mac' },
    { keys: ['Ctrl+Shift+%'], desc: 'Percentage format', winMac: 'Win/Mac' },
    { keys: ['Ctrl+Shift+!'], desc: 'Number format', winMac: 'Win/Mac' },
  ]},
  { category: 'Formulas', items: [
    { keys: ['Alt+='], desc: 'AutoSum', winMac: 'Win/Mac' },
    { keys: ['F9'], desc: 'Calculate all', winMac: 'Win/Mac' },
    { keys: ['F2'], desc: 'Edit cell / enter formula', winMac: 'Win/Mac' },
    { keys: ['F4'], desc: 'Cycle reference types', winMac: 'Win/Mac' },
    { keys: ['Ctrl+Shift+U'], desc: 'Expand formula bar', winMac: 'Win/Mac' },
  ]},
  { category: 'Tables', items: [
    { keys: ['Ctrl+T'], desc: 'Format as Table', winMac: 'Mac: Cmd+T' },
    { keys: ['Alt+;'], desc: 'Select visible cells only', winMac: 'Mac: Cmd+Shift+Z' },
    { keys: ['Alt+='], desc: 'Total row toggle in Table', winMac: 'Mac: Option+=' },
  ]},
  { category: 'General', items: [
    { keys: ['Alt'], desc: 'Show Key Tips (ribbon shortcuts)', winMac: 'Win/Mac' },
    { keys: ['Esc'], desc: 'Cancel / close', winMac: 'Win/Mac' },
    { keys: ['Tab'], desc: 'Move right', winMac: 'Win/Mac' },
    { keys: ['Shift+Tab'], desc: 'Move left', winMac: 'Win/Mac' },
    { keys: ['Enter'], desc: 'Move down', winMac: 'Win/Mac' },
    { keys: ['Alt+Enter'], desc: 'New line in cell', winMac: 'Mac: Ctrl+Option+Enter' },
    { keys: ['Ctrl+;'], desc: 'Insert today\'s date', winMac: 'Mac: Cmd+;' },
    { keys: ['Ctrl+Shift+;'], desc: 'Insert current time', winMac: 'Mac: Cmd+Shift+;' },
  ]},
];

const MostUseful20 = [
  ['Ctrl+S', 'Save'],
  ['Ctrl+C / Ctrl+V', 'Copy / Paste'],
  ['Ctrl+Z', 'Undo'],
  ['Ctrl+F', 'Find'],
  ['Ctrl+Home', 'Go to A1'],
  ['Ctrl+Arrow', 'Go to data edge'],
  ['Ctrl+Space', 'Select column'],
  ['Shift+Space', 'Select row'],
  ['Ctrl+T', 'Format as Table'],
  ['Alt+=', 'AutoSum'],
  ['F4', 'Cycle reference types'],
  ['Ctrl+D', 'Fill down'],
  ['F2', 'Edit cell'],
  ['Ctrl+1', 'Format Cells'],
  ['Ctrl+B', 'Bold'],
  ['Ctrl+;', 'Insert date'],
  ['Alt+Enter', 'New line in cell'],
  ['Ctrl+Shift+$', 'Currency format'],
  ['Ctrl+PageUp/Down', 'Switch sheets'],
  ['Esc', 'Cancel'],
];