const {test,expect}=require('@playwright/test');
const pages=[['home','Make sense of the cells. Then make them work.'],['dashboard','A little progress, every time.'],['curriculum','Build your spreadsheet fluency.'],['learn/track-fundamentals','Spreadsheet fundamentals'],['learn/track-fundamentals/micro-fundamentals-1','Cell addresses'],['practice','A small problem. A real skill.'],['lab','A little room to experiment.'],['projects','Turn a dataset into a decision.'],['formulas','The right function, within reach.'],['shortcuts','Less reaching. More flow.'],['errors','An error is a clue.'],['progress','Skills grow through practice.'],['settings','Make this space work for you.'],['assessment','Start where it feels useful.']];
for(const width of [1440,1024,768,390]){
 test.describe(`${width}px layout`,()=>{
  test.use({viewport:{width,height:900}});
  for(const [route,title] of pages)test(route,async({page},testInfo)=>{
   const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#'+route);await expect(page.getByRole('heading',{level:1,name:title,exact:true})).toBeVisible();
   expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
   expect(await page.locator('.view.active').count()).toBe(1);expect(errors).toEqual([]);
   if(width<800){await expect(page.locator('#sidebar')).toHaveJSProperty('inert',true);await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.getByRole('navigation',{name:'Main navigation'})).toBeVisible();await expect(page.locator('#menuToggle')).toHaveAttribute('aria-expanded','true');await expect(page.locator('#sidebar .nav-link').first()).toBeFocused();await page.keyboard.press('Escape');await expect(page.locator('#sidebar')).toHaveJSProperty('inert',true);await expect(page.locator('#menuToggle')).toBeFocused();}
   await page.screenshot({path:testInfo.outputPath('screen.png'),fullPage:false,animations:'disabled'});
  });
 });
}
test('lesson note, bookmark, checkpoint and completion survive reload',async({page})=>{
 await page.goto('/#learn/track-fundamentals/micro-fundamentals-1');await page.getByRole('button',{name:'Bookmark',exact:true}).click();await page.getByText('Your notes',{exact:true}).click();await page.getByRole('textbox',{name:'Notes for this lesson'}).fill('<b>My literal note</b>');await page.getByRole('button',{name:'A cell address combines a column letter and a row number.',exact:true}).click();await expect(page.locator('#quizFeedback')).toContainText('Correct.');await page.getByRole('button',{name:'Mark complete',exact:true}).click();await page.reload();await expect(page.getByRole('button',{name:'✓ Completed',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Remove bookmark'})).toHaveAttribute('aria-pressed','true');await page.getByText('Your notes',{exact:true}).click();await expect(page.locator('#lessonNotes')).toHaveValue('<b>My literal note</b>');expect(await page.locator('#lessonNotes b').count()).toBe(0);
});
test('focus timer off, Escape, and theme persistence',async({page})=>{await page.goto('/#settings');await page.getByLabel('Focus timer duration').selectOption('0');await page.getByRole('combobox',{name:'Color theme'}).selectOption('dark');await page.goto('/#learn/track-fundamentals/micro-fundamentals-1');await page.getByRole('button',{name:'Focus mode',exact:true}).click();await expect(page.locator('#focusTimer')).toHaveText('Timer off');await expect(page.locator('#focusOverlay')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#focusOverlay')).not.toBeVisible();await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');});
test('global search and reference filters are functional',async({page})=>{await page.goto('/');await page.getByRole('textbox',{name:'Search the academy'}).fill('absolute');await expect(page.locator('#searchResults')).toContainText('Absolute references');await page.locator('#searchResults').getByRole('link',{name:'Absolute references Lesson · Formula foundations',exact:true}).click();await expect(page.getByRole('heading',{level:1,name:'Absolute references',exact:true})).toBeVisible();await page.goto('/#formulas');await page.getByRole('textbox',{name:'Search functions'}).fill('XLOOKUP');await expect(page.locator('#formulaRows details')).toHaveCount(1);await page.locator('#formulaRows summary').click();await expect(page.locator('#formulaRows')).toContainText('Not available in Excel 2016/2019');await page.goto('/#shortcuts');await page.getByLabel('Operating system').selectOption('mac');await page.getByRole('textbox',{name:'Search shortcuts'}).fill('copy');await expect(page.locator('#shortcutRows')).toContainText('Command + C');});
async function exercise(page,title){await page.goto('/#practice');await page.getByRole('textbox',{name:'Search exercises'}).fill(title);await page.locator('#practiceRows').getByRole('button',{name:/Practice/}).first().click();await expect(page.locator('#view-lab')).toHaveClass(/active/);}
async function formula(page,text){await page.getByRole('textbox',{name:'Formula or value',exact:true}).fill(text);await page.getByRole('button',{name:'Apply',exact:true}).click();}
async function go(page,ref){await page.getByRole('textbox',{name:'Cell or range',exact:true}).fill(ref);await page.getByRole('textbox',{name:'Cell or range',exact:true}).press('Enter');}
test('formula validation, reset, undo, redo and persistence',async({page})=>{await exercise(page,'Total revenue');await formula(page,'=SUM(Data!G2:G61)');await page.getByRole('button',{name:'Check answer',exact:true}).click();await expect(page.locator('#exerciseFeedback')).toContainText('Correct.');await expect(page.getByRole('textbox',{name:'B3',exact:true})).toHaveValue('11640');await page.getByRole('button',{name:'Reset',exact:true}).click();await expect(page.getByRole('textbox',{name:'B3',exact:true})).toHaveValue('');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('textbox',{name:'B3',exact:true})).toHaveValue('11640');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.getByRole('textbox',{name:'B3',exact:true})).toHaveValue('');await page.getByRole('button',{name:'Undo',exact:true}).click();await page.reload();await expect(page.getByRole('textbox',{name:'B3',exact:true})).toHaveValue('11640');});
test('relative fill, selection and keyboard editing',async({page})=>{await exercise(page,'Fill a relative reference');await go(page,'C2');await formula(page,'=A2*B2');await go(page,'C2:C5');await page.getByRole('button',{name:'Fill down',exact:true}).click();await page.getByRole('button',{name:'Check answer',exact:true}).click();await expect(page.locator('#exerciseFeedback')).toContainText('Correct.');await expect(page.getByRole('textbox',{name:'C5',exact:true})).toHaveValue('200');await page.getByRole('textbox',{name:'C5',exact:true}).press('ArrowRight');await expect(page.locator('#cellAddress')).toHaveValue('D5');await page.getByRole('textbox',{name:'D5',exact:true}).press('F2');await page.keyboard.type('=2+3');await page.keyboard.press('Enter');await expect(page.getByRole('textbox',{name:'D5',exact:true})).toHaveValue('5');});
test('formatting and sort-state exercises',async({page})=>{await exercise(page,'Format a ratio');await formula(page,'0.15');await page.getByLabel('Cell format',{exact:true}).selectOption('percent');await page.getByRole('button',{name:'Check answer',exact:true}).click();await expect(page.locator('#exerciseFeedback')).toContainText('Correct.');await expect(page.getByRole('textbox',{name:'B3',exact:true})).toHaveValue('15%');await exercise(page,'Sort whole records');await go(page,'A2:B5');await page.getByRole('button',{name:'Sort range A–Z'}).click();await page.getByRole('button',{name:'Check answer',exact:true}).click();await expect(page.locator('#exerciseFeedback')).toContainText('Correct.');});
test('sheet management, accessible resizing and formula updates on rename',async({page})=>{await exercise(page,'Total revenue');await formula(page,'=SUM(Data!G2:G61)');await page.getByRole('tab',{name:'Data',exact:true}).click();await page.getByRole('button',{name:'Rename',exact:true}).click();await page.getByLabel('Sheet name').fill('Sales data');await page.getByRole('button',{name:'Save name'}).click();await page.getByRole('tab',{name:'Analysis',exact:true}).click();await expect(page.getByRole('textbox',{name:'B3',exact:true})).toHaveValue('11640');await go(page,'B3');await expect(page.locator('#formulaInput')).toHaveValue("=SUM('Sales data'!G2:G61)");await page.getByRole('button',{name:'Cell size'}).click();await page.getByLabel('Column width (60–400 pixels)').fill('160');await page.getByLabel('Row height (30–140 pixels)').fill('40');await page.getByRole('button',{name:'Apply size'}).click();expect(await page.locator('[data-ref="B3"]').evaluate(e=>e.getBoundingClientRect().width)).toBeGreaterThanOrEqual(159);await page.getByRole('button',{name:'Add sheet'}).click();await expect(page.getByRole('tab')).toHaveCount(3);await page.getByRole('button',{name:'Remove',exact:true}).click();await expect(page.getByRole('tab')).toHaveCount(2);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('tab')).toHaveCount(3);});
test('CSV import, invalid import feedback, and downloads',async({page})=>{await page.goto('/#lab');await page.getByLabel('Import CSV',{exact:true}).setInputFiles({name:'sample.csv',mimeType:'text/csv',buffer:Buffer.from('Name,Value\n"A, B",12\nSafe,"=1+1"')});await expect(page.getByRole('textbox',{name:'A2',exact:true})).toHaveValue('A, B');await expect(page.getByRole('textbox',{name:'B3',exact:true})).toHaveValue('=1+1');const csvDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV',exact:true}).click();const csv=await csvDownload;expect(csv.suggestedFilename()).toBe('practice.csv');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export workbook',exact:true}).click();const file=await download;expect(file.suggestedFilename()).toBe('workbook.json');await page.getByLabel('Import workbook',{exact:true}).setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":999}')});await expect(page.locator('#toastContainer')).toContainText('Import failed');await page.getByLabel('Import workbook',{exact:true}).setInputFiles(await file.path());await expect(page.getByRole('textbox',{name:'A2',exact:true})).toHaveValue('A, B');});
test('projects open their own brief, workbook and saved reflection',async({page})=>{await page.goto('/#projects/p4');await expect(page.getByRole('heading',{level:1,name:'Six-month retail report'})).toBeVisible();await page.getByLabel('Project reflection').fill('Reconciled the region totals.');await page.getByRole('button',{name:'Mark project complete'}).click();await page.reload();await expect(page.getByLabel('Project reflection')).toHaveValue('Reconciled the region totals.');await expect(page.getByRole('button',{name:'✓ Project completed'})).toBeVisible();await page.getByRole('button',{name:'Open project workbook'}).click();await expect(page.locator('#sheetGrid')).toBeVisible();await expect(page.getByRole('textbox',{name:'A2',exact:true})).toHaveValue('ORD-1001');});
for(const width of [1440,390])test(`dark lab ${width}`,async({page},testInfo)=>{await page.setViewportSize({width,height:900});await page.goto('/#lab');await page.getByRole('button',{name:'Switch color theme'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await page.screenshot({path:testInfo.outputPath('dark-lab.png'),animations:'disabled'});});

test('search opens a function when already on its reference page',async({page})=>{await page.goto('/#formulas');await page.getByRole('textbox',{name:'Search the academy'}).fill('XLOOKUP');await page.locator('#searchResults').getByRole('link',{name:'XLOOKUP Function reference',exact:true}).click();await expect(page.locator('#formulaSearch')).toHaveValue('XLOOKUP');await expect(page.locator('#formulaRows details')).toHaveCount(1);await expect(page.locator('#searchResults')).toBeHidden();});
