const test=require('node:test'),assert=require('node:assert/strict'),load=require('./helpers.cjs');
const {run}=load();
const calc=(formula,cells={})=>run(`(()=>{const w=seedWorkbook();w.sheets[1].cells=${JSON.stringify({...cells,Z120:{raw:formula}})};return SheetEngine.calculator(w).get(w.sheets[1],'Z120');})()`);
const cases=[['=2+3*4',14],['=(2+3)*4',20],['=2^3^2',64],['=15%',.15],['=SUM(1,2,3)',6],['=AVERAGE(2,4,6)',4],['=COUNT(1,"x",3)',2],['=COUNTA(1,"x",3)',3],['=ROUND(1.236,2)',1.24],['=IF(TRUE,42,1/0)',42],['=IF(FALSE,1/0,7)',7],['=IFERROR(1/0,"Fix")','Fix'],['=AND(TRUE,FALSE)',false],['=OR(TRUE,FALSE)',true],['=LEFT("Order",3)','Ord'],['=RIGHT("Order",2)','er'],['=MID("AB123",3,3)','123'],['=TRIM("  a   b  ")','a b'],['=LEN("abc")',3],['=FIND("b","abc")',2],['=SEARCH("B","abc")',2],['=CONCAT("a","b")','ab'],['=TEXTJOIN(" / ",TRUE,"a","b")','a / b'],['=DATE(2026,3,1)',46082],['=YEAR(DATE(2026,3,1))',2026],['=MONTH(DATE(2026,3,1))',3],['=DAY(DATE(2026,3,1))',1],['=1/0','#DIV/0!'],['=MISSING(1)','#NAME?'],['=1+"x"','#VALUE!'],['=Data!G2',36],['=XLOOKUP("ORD-1010",Data!A2:A61,Data!G2:G61)',24],['=XLOOKUP("absent",Data!A2:A61,Data!G2:G61,"Missing")','Missing']];
for(const [formula,expected] of cases)test(formula,()=>assert.equal(calc(formula),expected));
test('ranges and criteria reconcile independently',()=>{const expected=run('Datasets.retail.rows.filter(r=>r[1]==="East"&&r[2]==="March").reduce((n,r)=>n+r[6],0)');assert.equal(calc('=SUMIFS(Data!G2:G61,Data!B2:B61,"East",Data!C2:C61,"March")'),expected);assert.equal(calc('=SUM(Data!G2:G61)'),run('Datasets.retail.rows.reduce((n,r)=>n+r[6],0)'));});
test('circular references and blank values',()=>{assert.equal(calc('=A1',{A1:{raw:'=Z120'}}),'#CIRC!');assert.equal(calc('=A1+3'),3);});
test('no executable JavaScript can be parsed',()=>{assert.equal(calc('=globalThis.process.exit()'),'#NAME?');assert.equal(calc('=SUM(1);alert(1)'),'#VALUE!');});
test('fill preserves quoted text and absolute references',()=>assert.equal(run(`SheetEngine.shift('=B2*$F$2+SUM(C2:C4)&"A1"',2)`),'=B4*$F$2+SUM(C4:C6)&"A1"'));
test('CSV quotes, commas and newlines round-trip',()=>{const rows=[['a,b','a"b','a\nb'],['1','2','3']];assert.deepEqual(JSON.parse(run(`JSON.stringify(SheetEngine.csvParse(SheetEngine.csvWrite(${JSON.stringify(rows)})))`)),rows);assert.throws(()=>run('SheetEngine.csvParse(\'"bad\')'));});
test('every exercise and project solution evaluates',()=>{const errors=JSON.parse(run(`JSON.stringify([...Exercises,...Projects.map(p=>({id:p.id,dataset:p.dataset,solution:p.solution}))].map(e=>[e.id,exerciseExpected(e)]).filter(([,v])=>typeof v==='string'&&v.startsWith('#')))`));assert.deepEqual(errors,[]);});

test('range limits apply to both endpoints',()=>{assert.equal(calc('=SUM(A9999999:A1)'),'#REF!');assert.equal(calc('=SUM(ZZ1:A1)'),'#REF!');});
